# Port to bind on
port = 5591

# Absolute path to private key to use when authenticating with servers.
# Can be either privkey or privkey || pubkey; only first 32 bytes will
# be used.
privkey_path = ""

# ZMQ servers to connect to and subscribe
[[servers]]

# Address of the server to connect to
address = "tcp://registration.refraction.network:5591"

# Type of authenticaton method to use when connecting. Can be NULL or CURVE
type = "CURVE"

# Public key of server to use if using CURVE authentication
# The default value is the public key for the API hosted at registration.refraction.network
pubkey = "s5gkB.U$dl]gO=F{Qo3=4Api-T$5#tpwaT/bSOr@"

# ZMQ subscription prefix for this server. Leave as "" to receive all messages
subscription = ""
